### ISSUE TITLE
Error in Log after setting Remote/status-flag  to true

### ISSUE THREAD

**Issue by mlapp** [TA2k/ioBroker.ford#1]
I use the adapter with the properties of StatusV4. When the Mustang Mach E changes the IgnitonStatus to "Run", I set the Remote/status flag to true to force an update. Everything works so far and the data is updated. But I get two errors in the log with every call:
1. Error: Request failed with status code 404
2. {"statusCode":404,"message":"Resource not found"}
I suspect that incorrect data is being retrieved here. I've only had this problem since version 0.0.7

**Comment by TA2k** [comment]
Can you please past also the url without vin which cause the error. The error should also occur when you start the adapter

**Comment by TA2k** [comment]
Maybe the remote control is not working for the car I added a new remote control refresh

**Comment by mlapp** [comment]
There are no error messages when the adapter is started.
Currently I can find these two URLs in the log, I hope this helps.

Error: getaddrinfo EAI_AGAIN api.mps.ford.com
https://api.mps.ford.com/api/fuel-consumption-info/v1/reports/fuel?vin=XXXXX
Error: getaddrinfo EAI_AGAIN usapi.cv.ford.com
</html>https://usapi.cv.ford.com/api/vehicles/v2/XXXXX/status

**Comment by TA2k** [comment]
This looks more like unreachable problem from the ford server
