### ISSUE TITLE
Fehler beim Starten der Instanz

### ISSUE THREAD

**Issue by kkeintzel** [TA2k/ioBroker.ford#12]
"<!doctype html>\n<html lang=\"en\"> \n <head> \n <meta id=\"fma-version\" version=\"fma-5.14.0\" version-url=\"https://www.account.ford.com/etc/fd/fma/manifest.json\"> \n <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"> \n <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \n <meta name=\"description\" content=\"Sign in or create your Ford account. Access all Ford has to offer in shopping, ownership, and mobility experiences with one single account.\"> \n <title>Ford - Sign In Or Create A New Account</title> \n <meta http-equiv=\"X-UA-Compatible\" content=\"IE=EDGE\"> \n <link id=\"favicon\" rel=\"shortcut icon\" type=\"image/x-icon\" href=\"https://www.account.ford.com/favicon.ico\"> \n <link id=\"completeStyle\" href=\"https://www.account.ford.com/static/css/main.f82f7279.chunk.css\" rel=\"stylesheet\"> \n <script type=\"text/javascript\" id=\"SCRIPT_RUNTIME\" src=\"https://www.account.ford.com/static/js/runtime-main.f4de8767.js\"></script> \n <script type=\"text/javascript\" id=\"SCRIPT_CHUNK\" src=\"https://www.account.ford.com/static/js/2.99769ea7.chunk.js\"></script> \n <script>\n\t \t\tconst versionElement = document.getElementById(\"fma-version\");\n\t \t\tconst jsonVersionURL = versionElement.getAttribute(\"version-url\");\n\t\t\tfetch(jsonVersionURL).then(res=>res.json()).then((jsonFile)=>{\n\t\t\t\t\t\t const fmaVersionMetaElement = document.getElementById(\"fma-version\");\n\t\t\t\t\t\t const fmaVersion = fmaVersionMetaElement.getAttribute(\"version\");\n\t\t\t\t\t\t const jsonVersion = jsonFile[\"fma.js\"].match(/fma-[0-9]*\\.[0-9]*\\.[0-9]*/);\n\t\t\t\t\t\t const templatesAreMismatched = jsonVersion != null && jsonVersion[0] != fmaVersion;\n\n\t\t\t\t\t\t if (templatesAreMismatched){\n\t\t\t\t\t\t\tconst errorHeader = document.createElement(\"h1\");\n\t\t\t\t\t\t\tconst errorText = document.createElement(\"h3\");\n\t\t\t\t\t\t\terrorHeader.innerText = \"AN ERROR OCCURED\";\n\t\t\t\t\t\t\terrorText.innerText = \"Please try again later.\";\n\t\t\t\t\t\t\terrorHeader.setAttribute(\"style\", \"padding-left:20px;\");\n\t\t\t\t\t\t\terrorText.setAttribute(\"style\", \"padding-left:20px;\");\n\t\t\t\t\t\t\tdocument.body.append(errorHeader);\n\t\t\t\t\t\t\tdocument.body.append(errorText);\n\t\t\t\t\t\t }});\n\t\t</script> \n \n<script>!function(){function o(n,i){if(n&&i)for(var r in i)i.hasOwnProperty(r)&&(void 0===n[r]?n[r]=i[r]:n[r].constructor===Object&&i[r].constructor===Object?o(n[r],i[r]):n[r]=i[r])}try{var n=decodeURIComponent(\"%7B%22secure_cookie%22%3A%20true%7D\");if(n.length>0&&window.JSON&&\"function\"==typeof window.JSON.parse){var i=JSON.parse(n);void 0!==window.BOOMR_config?o(window.BOOMR_config,i):window.BOOMR_config=i}}catch(r){window.console&&\"function\"==typeof window.console.error&&console.error(\"mPulse: Could not parse configuration\",r)}}();</script>\n <script>!function(a){var e=\"https://s.go-mpulse.net/boomerang/\",t=\"addEventListener\";if(\"False\"==\"True\")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e=\"https://s2.go-mpulse.net/boomerang/\";if(window.BOOMR_API_key=\"QUF9E-G6ZRH-BKQBG-NXC6F-BBKP5\",function(){function n(e){a.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!a.BOOMR||!a.BOOMR.version&&!a.BOOMR.snippetExecuted){a.BOOMR=a.BOOMR||{},a.BOOMR.snippetExecuted=!0;var i,_,o,r=document.createElement(\"iframe\");if(a[t])a[t](\"load\",n,!1);else if(a.attachEvent)a.attachEvent(\"onload\",n);r.src=\"javascript:void(0)\",r.title=\"\",r.role=\"presentation\",(r.frameElement||r).style.cssText=\"width:0;height:0;border:0;display:none;\",o=document.getElementsByTagName(\"script\")[0],o.parentNode.insertBefore(r,o);try{_=r.contentWindow.document}catch(O){i=document.domain,r.src=\"javascript:var d=document.open();d.domain='\"+i+\"';void(0);\",_=r.contentWindow.document}_.open()._l=function(){var a=this.createElement(\"script\");if(i)this.domain=i;a.id=\"boomr-if-as\",a.src=e+\"QUF9E-G6ZRH-BKQBG-NXC6F-BBKP5\",BOOMR_lstart=(new Date).getTime(),this.body.appendChild(a)},_.write(\"<bo\"+'dy onload=\"document._l();\">'),_.close()}}(),\"\".length>0)if(a&&\"performance\"in a&&a.performance&&\"function\"==typeof a.performance.setResourceTimingBufferSize)a.performance.setResourceTimingBufferSize();!function(){if(BOOMR=a.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var e=\"\"==\"true\"?1:0,t=\"\",n=\"2rb6rzaxacxiuy2wxf6a-f-a0fc8022c-clientnsv4-s.akamaihd.net\",i=\"false\"==\"true\"?2:1,_={\"ak.v\":\"33\",\"ak.cp\":\"585058\",\"ak.ai\":parseInt(\"569279\",10),\"ak.ol\":\"0\",\"ak.cr\":51,\"ak.ipv\":4,\"ak.proto\":\"http/1.1\",\"ak.rid\":\"d77eb92\",\"ak.r\":31092,\"ak.a2\":e,\"ak.m\":\"a\",\"ak.n\":\"essl\",\"ak.bpcip\":\"212.67.232.0\",\"ak.cport\":55754,\"ak.gh\":\"23.0.174.134\",\"ak.quicv\":\"\",\"ak.tlsv\":\"tls1.3\",\"ak.0rtt\":\"\",\"ak.csrc\":\"-\",\"ak.acc\":\"reno\",\"ak.t\":\"1666627964\",\"ak.ak\":\"hOBiQwZUYzCg5VSAfCLimQ==DRdjyzVM5GErZohyx26mK6z0i4M3F8FpOj9vtIrSE2tUucCBPs96N06KQ30/rHl9K5mCjEQxjhQZw6gPFzXuihT7FHl/UCqcSzRbdavTB5DFO4JmioZZVMKZGnHiWd/MMIbJgFMo9ov48eFHNr+wvjx3yNJHAHxGgu1If7SE3qspD9co5JGF+MtIVaCV/QpQ+O2FU27Yf0+lzdo206x6RP5CO/U2SXDRC0Vu1DGnZpHbiBb9GkpgZnVHtSzrFlgsrugHUcBb0hb9s070FULduL5bsUTzjx8WavMZvfavEyThVoYWEWiuUBfxyzO2lcLx2PPPLYVd1X+psS8yFK+m/18SoeEAGZep8+fDcwYkUq/JrRZCOWICByQTuGLrktMOV9Shl9TUNt3KfYoLqX1v+HcEhrTL+ID1XWDx9GIxdPU=\",\"ak.pv\":\"161\",\"ak.dpoabenc\":\"\",\"ak.tf\":i};if(\"\"!==t)_[\"ak.ruds\"]=t;var o={i:!1,av:function(e){var t=\"http.initiator\";if(e&&(!e[t]||\"spa_hard\"===e[t]))_[\"ak.feo\"]=void 0!==a.aFeoApplied?1:0,BOOMR.addVar(_)},rv:function(){var a=[\"ak.bpcip\",\"ak.cport\",\"ak.cr\",\"ak.csrc\",\"ak.gh\",\"ak.ipv\",\"ak.m\",\"ak.n\",\"ak.ol\",\"ak.proto\",\"ak.quicv\",\"ak.tlsv\",\"ak.0rtt\",\"ak.r\",\"ak.acc\",\"ak.t\",\"ak.tf\"];BOOMR.removeVar(a)}};BOOMR.plugins.AK={akVars:_,akDNSPreFetchDomain:n,init:function(){if(!o.i){var a=BOOMR.subscribe;a(\"before_beacon\",o.av,null,null),a(\"onbeacon\",o.rv,null,null),o.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head> \n <body> \n <noscript>\n You need to enable JavaScript to run this app. \n </noscript> \n <div class=\"ibm-ci-data-container\" data-ibm-login-url=\"/authsvc/mtfim/sps/authsvc?identity_source_id=75d08ad1-510f-468a-b69b-5ebc34f773e3&StateId=6fb6551e-4c4b-4a65-87d9-b1ddbbe864e2\" data-ibm-login-error-text=\"CSIAH0320E Der Account ist inaktiviert. Wenden Sie sich an Ihren Administrator.\"></div> \n <div id=\"page\"></div> \n <script type=\"text/javascript\" id=\"SCRIPT_MAIN\" src=\"https://www.account.ford.com/static/js/main.34a349c2.chunk.js\"></script> \n <script>\n\t\t /*\n\t\t\t* disable react dev tools in production env\n\t\t\t*/\n\t\t\t(function disableReactDevTools() {\n\t\t\t\tif (\n\t\t\t\t\t!!window.__REACT_DEVTOOLS_GLOBAL_HOOK__ &&\n\t\t\t\t\ttypeof window.__REACT_DEVTOOLS_GLOBAL_HOOK__ === 'object' &&\n\t\t\t\t\t(\n\t\t\t\t\t\twindow.location.hostname.indexOf('sso.ci.ford.com') > -1 ||\n\t\t\t\t\t\twindow.location.hostname.indexOf('sso.ci.lincoln.com') > -1\n\t\t\t\t\t)\n\t\t\t\t) {\n\t\t\t\t\twindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.inject = function () {};\n\t\t\t\t}\n\t\t\t})();\n\t\t</script> \n </body>\n</html>"

**Comment by TA2k** [comment]
Version 0.0.12 funktioniert bei mir

**Comment by kkeintzel** [comment]
Danke für die schnelle Info - Sieht aus als hätte ich ein Problem mit meinem Ford-Account. Komme jetzt in die APP/Web auch nicht mehr rein.
