### ISSUE TITLE
404 Not Found: Requested route ('my-garage-eu-prod.apps.pd01.uswest.cf.ford.com') does not exist.\n"

### ISSUE THREAD

**Issue by kkeintzel** [TA2k/ioBroker.ford#13]
Beim Starten des Adapters (v0.0.12) bekomme ich im LOG folgenden Fehler:
![Bildschirmfoto 2022-11-13 um 13 50 05](https://user-images.githubusercontent.com/83504161/201522558-92f30639-7e4a-4d43-acf5-d4b7641a7dbd.png)

Der Adapter ist grün und es sieht aus als ob alles funktionieren würde.
Vielleicht kannst Du trotzdem mal einen Blick drauf werfen - Danke

FYI:
 Sollte jemand nicht mehr einloggen können iob, web(ford), app(ford)  und folgende Meldung erhalten:
![Bildschirmfoto 2022-11-02 um 13 00 22](https://user-images.githubusercontent.com/83504161/201522752-67a96906-8ea5-445b-b110-a60269f7d929.png)

... hat Ford deinen Account wegen ThirdParty-SW abfragen
GESPERRT !!!

**Comment by TA2k** [comment]
habe in der GitHub version den detail call rausgenommen
Wann wird denn der Account gesperrt wie oft hast du abgefragt?

**Comment by kkeintzel** [comment]
Danke für die Anpassung. 
Hatte den Adapter seit ca. 02/2022 mit einem 5min Intervall ohne Probleme laufen.
Vor 22 Tagen haben Sie mich gesperrt. Hatte den Issue #12  damals eröffnet.
Nach mehrere eMails & Telefonaten mit Fordpass-Support und Bekräftignung keine 3rd Party Abfragen mehr zu tätigen, hat Ford meinen Account wieder entsperrt.
Jetzt habe ich mir sicherheitshalber einen zusätzlichen Ford-Account erstellt, der auch Zugriff auf meinen Mustang Mach E hat um wieder den Adapter aktivieren zu können.

**Comment by TA2k** [comment]
Ich habe mal die user agents angepasst steht denn unter statusv2 noch brauchbare infos?

**Comment by TA2k** [comment]
Kannst du nochmal checken ob die aktuelle GitHub version bei dir so funktioniert
