### ISSUE TITLE
12V-Batterieüberwachung

### ISSUE THREAD

**Issue by AGrillenberger** [TA2k/ioBroker.ford#21]
Ich habe nun mal ein neues Issue zu der 12V-Batterieüberwachung aus dem 403-Error-Issue (https://github.com/TA2k/ioBroker.ford/issues/18#issuecomment-1732396283_) geöffnet der Übersichtlichkeit halber.

Wie schon beschrieben, geht bei mir der 12V-Wert regelmässig beim Ausschalten unter die 12.2V, sodass der Adapter deaktiviert hat. Ich habe das bei mir nun daher temporär herausprogrammiert.

Zum Nachvollziehen hier nun mal ein Log des statusQuery.metrics.batteryVoltage.value:
<img width="273" alt="Screenshot 2023-09-24 at 11 34 14" src="https://user-images.githubusercontent.com/533185/270156220-732fc532-0f55-4e20-8e0f-7cea62f11eb8.png">

In dem Fall war es so, dass ich das Fahrzeug an der AC-Wallbox hatte, um 10:51 Uhr abgesteckt und dann direkt losgefahren. Um 10:59 am Ziel das Fahrzeug abgestellt, dabei ging die Battery-Voltage kurz unter 12.2V (sodass der Adapter sich beendet hätte), erholte sich aber (ohne dass geladen wurde) sofort wieder, bei der nächsten Änderung war wieder alles gut.

Unterschied zu dem was ich bisher dachte ist, dass es erst beim Abstellen des Fahrzeugs auftrat, bislang war mein Eindruck, dass es direkt beim Abstecken geschieht. Unabhängig davon scheint es sich aber um sehr kurze Spannungsabfälle zu handeln, die "von aussen bedingt" scheinen. Entsprechend wäre mein Vorschlag, zumindest 2 Minuten oder Ähnliches zu warten, bevor deaktiviert wird, um solche Fälle abzufangen.

Ich werde weiter beobachten und ggf. weitere Daten nachliefern. Für mich persönlich nicht dringlich, da ich die Überwachung wie gesagt rausgenommen habe, aber vielleicht für andere hilfreich.

**Comment by TA2k** [comment]
0.1.4 check ob zweimal hintereinander unter 12.1V

**Comment by mlapp** [comment]
Könntest du die Prüfung evtl. nur optional aktivieren. Vielleicht sogar über den Admin als Checkbox oder so?
Mein Mach E hat regelmäßig eine Batteriespannung knapp unter 12V. Die Batterie wird aus dem HV-Akku nachgeladen, wenn die Spannung zu weit abfällt. Von daher ist die Prüfung der Batteriespannung eher von Nachteil. 
Wichtig ist nur, dass die Datenabfrage weiterhin die Daten nur vom Server abruft und nicht jedes mal von Auto angefordert wird. 
Dann belastet der Adapter den 12V Akku faktisch ja nicht.

**Comment by TA2k** [comment]
habs nochmal angepasst in 0.1.5

**Comment by mlapp** [comment]
Perfekt. Dank dir.
Hab die neue Version gerade installiert und werde jetzt testen.

**Comment by weindler** [comment]
> habs nochmal angepasst in 0.1.5

Ich teste mit, aber eine Sache wäre noch, könntest du dir im Admin unter den Einstellungen die Seite Mal in Firefox oder Chrome anschauen. Das mit den 12v ist ewig groß und wo man die Haken setzen kann zum deaktivieren der 12v kann man nichts lesen da alles überlappt ist, kann dir morgen Mal einen Screen machen, wenn du ihn brauchst

**Comment by root01** [comment]
Nur mal kurz für mich zum Verständnis, wenn ich den Checkbox "Update vom Fahrzeug anfordern" aus habe, werden nur Daten vom Ford server Empfangen?

**Comment by mlapp** [comment]
Ja. Das ist auch die einzig sinnvolle Option. Wenn die Checkbox aktiviert ist, dann sperrt Ford deinen Account innerhalb weniger Stunden/Tage. Zumindest wenn du ein kurzes Abruf-Intervall aktiviert hast. 
Ich rufe die Daten im Minutentakt ab, allerdings habe ich die Checkbox nicht aktiviert.
Damit bekommst du immer die aktuellsten Daten, die das Auto an den Server gesendet hat und Ford sperrt deinen Account nicht.

**Comment by root01** [comment]
Wenn Ford den Account gesperrt hat, kann man den dann auch wieder entsperren? Ich hatte das Intervall auf 15min gestellt mit checkbox an und kann die Daten in meiner App nicht mehr händisch aktualisieren.

**Comment by mlapp** [comment]
Du selbst kannst das nicht. Du kannst Ford anschreiben und darum bitten.
Erfahrungsgemäß dauert das dann aber relativ lang UND in der Vergangenheit war es oft so, dass dir Ford damit gedroht hat, deinen Account bei weiteren "Verstößen" komplett zu deaktivieren.
Weitaus einfacher ist es, einen neuen Account anzulegen, das Auto auf diesen zu übernehmen und in Zukunft den Abfragequatsch gegen das Auto zu lassen. Das kannst du selbst erledigen, es geht sehr schnell (auch wenn du dann das Auto und die App neu konfigurieren musst) und du weckst bei Ford keine schlafenden Hunde.
