### ISSUE TITLE
GPS Standort Daten des Autos

### ISSUE THREAD

**Issue by dadsche** [TA2k/ioBroker.ford#23]
Hallo,

seit dem Update auf die Version 0.1.5 kann ich die GPS Standort Daten des Autos nicht mehr finden.
Wo sind diese nun "versteckt" oder gibt es diese nicht mehr?

**Comment by wolfgang2101** [comment]
Hi,
werden bei mir unter
ford.0.XXXXXXXXXX.statusQuery.metrics.position.value.location
aufgelistet.

**Comment by dadsche** [comment]
Vielen Danke!
Jetzt habe ich es auch gefunden.
Ich habe nur nach "GPS", "Latitude" und "Longitude" gesucht und dann die abgekürzten Positionen nicht gefunden.
