### ISSUE TITLE
Fehlermeldung bricht Aktualisierung ab...

### ISSUE THREAD

**Issue by McGoerky** [TA2k/ioBroker.ford#24]
Bei mir läuft die Version 0.1.5. mit 2 registrierten Fahrzeugen.
Eines davon ist aktuell und eines ist älter. (rd. 10 Jahre)

Für das ältere Fahrzeug bekomme ich in regelmäßigem Abstand (5min) diese Fehlermeldungen.
Das Problem ist, das dadurch auch die Aktualisierung des anderes Fahrzeuges abbricht.

Gibt es hierfür eine Lösung?

> <html>
<body>

ford.0 | 2023-10-28 15:00:19.205 | error | {"code":404,"error":"not found","message":"No vehicle found with vin: WF0CXXGXXXXXXXXXX","messageTemplate":"No vehicle found with vin: {vin}","messageParams":{"vin":"WF0CXXGXXXXXXXXXX"},"timestamp":"2023-10-28T13:00:19.090874Z","referenceId":"f432f95c85730xxxxxxxxxxxxxxxxxxxx"}
-- | -- | -- | --
ford.0 | 2023-10-28 15:00:19.204 | error | AxiosError: Request failed with status code 404
ford.0 | 2023-10-28 15:00:19.203 | error | Failed to force update

</body>
</html>

**Comment by TA2k** [comment]
Gibt es nicht die Möglichkeit das andere Fahrzeug aus dem account zu entfernen

**Comment by McGoerky** [comment]
Ist jetzt wirklich nicht böse gemeint und mit vollem Respekt für Deine Arbeit.
Ist es mein Fehler das ich 2 Fahrzeuge der Firma besitze und diese in der Ford App verwalte? Oder ist es ein Bug in dem Adapter der dazu führt das die Daten nicht aktualisiert werden?

Dann schließe bitte einfach diesen Issue-Report und ich werde den Adapter deinstallieren.
Danke Dir trotzdem und einen schönen Abend.

**Comment by TA2k** [comment]
Ok aber eigentlich sollte der fehlhafte Aktualisierung eine anderes Fahrzeug nicht beeinträchtigen aber das sieht man detailliert im debug log

**Comment by McGoerky** [comment]
Also mit LOG Einstellung silly:

Interessant finde ich den Eintrag: "Command in progress" für das neuere Fahrzeug.
Kann es sein das hier ein Prozessschritt nicht abgeschlossen wird?

Beim Neustart des Adapter funktioniert das Abrufen der Daten genau einmal. Danach nicht mehr..

Dann wäre dieser Fehler aber in der Ford API.

> <html>
<body>


ford.0 | 2023-10-28 20:05:05.150 | debug | Updating statusQuery for WF03XXTTGXXXXXX67
-- | -- | -- | --
ford.0 | 2023-10-28 20:05:05.144 | debug | {"id":"7d2fc2b4-XXXX-4145-XXXX-8aecc75d1464","target":{"vehicleId":"795b217d-XXXX-XXXX-XXXX-c352e191f2fe","vin":"WF03XXTTGXXXXXX67","deviceId":"e97eaaae-0a61-433b-8637-b82b18779d06"},"type":"statusRefresh","currentStatus":"REQUESTED","statusReason":"Command in progress","createTime":"2023-10-28T18:05:05.003629Z","updateTime":"2023-10-28T18:05:05.003629Z","expireTime":"2023-10-28T18:06:35.003629Z","failIfPrecluded":false,"wakeUp":true}
ford.0 | 2023-10-28 20:05:05.135 | debug | Updating statusQuery for WF0CXXGAKXXXXXX44
ford.0 | 2023-10-28 20:05:05.134 | error | {"code":404,"error":"not found","message":"No vehicle found with vin: WF0CXXGAKXXXXXX44","messageTemplate":"No vehicle found with vin: {vin}","messageParams":{"vin":"WF0CXXGAKXXXXXX44"},"timestamp":"2023-10-28T18:05:05.015846Z","referenceId":"9d3e1fc2ed9546c4021709508d623b13"}
ford.0 | 2023-10-28 20:05:05.133 | error | AxiosError: Request failed with status code 404
ford.0 | 2023-10-28 20:05:05.132 | error | Failed to force update
ford.0 | 2023-10-28 20:05:04.195 | debug | Force update of WF0CXXGAKXXXXXX44
ford.0 | 2023-10-28 20:05:04.171 | debug | Force update of WF03XXTTGXXXXXXX67


</body>
</html>

**Comment by TA2k** [comment]
kommt drauf was da noch im log steht wird es vielleicht wegen 12v blockiert wird allgemein ist force refresh bei ford gefährlich
