### ISSUE TITLE
Adapter verbindet sich nach Update auf Node.js 18.18.2 nicht mehr

### ISSUE THREAD

**Issue by wetterandi** [TA2k/ioBroker.ford#26]
Ich verwende die Version 0.1.5 des Adapters.

Ich habe gestern das Update des iobrokers auf Node.js 18.18.2 durchgeführt.

Dazu habe ich den neuen Befehl 

iob nodejs-update

verwendet und bin vorgegangen, wie in

[https://forum.iobroker.net/topic/69067/neuer-befehl-iob-nodejs-update](url)

beschrieben.

Seitdem verbindet sich der Adapter nicht mehr mit Ford. Sicherheitshalber habe ich die FordPass Zugangsdaten nochmal neu eingegeben, weil ich die Fehlermeldung so gelesen habe, dass er meine Zugangsdaten nicht hat. Aber das hat leider nichts gebracht.

Die FordPass - App und das Web erreiche ich. Mein Zugang scheint also nicht gesperrt zu sein :-)

Ich bekomme folgende Fehlermeldungen:

`AxiosError: Request failed with status code 400`

`"<!doctype html><!--\n Macro Substitution Values:\n ERROR_CODE: invalid_client\n ERROR_DESCRIPTION: CSIAQ0154E Das System kann den Client mit ID [9fb503e0-715b-47e8-adfd-ad4b7770f73b] nicht finden.\n -->\n<html ng-app=\"app\">\n <head><!-- FMA - Version: 5.32.0 Timestamp: 10/06/2023 14:11:04 -->\n <meta id=\"fma-version\" version=\"fma-5.32.0\" version-url=\"https://www.account.ford.com/etc/fd/fma/manifest.json\">\n <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n <meta name=\"description\" content=\"Sign in or create your Ford account. Access all Ford has to offer in shopping, ownership, and mobility experiences with one single account.\">\n <title>Ford - Sign In Or Create A New Account</title>\n <meta http-equiv=\"X-UA-Compatible\" content=\"IE=EDGE\">\n <link id=\"favicon\" rel=\"shortcut icon\" type=\"image/x-icon\" href=\"https://www.account.ford.com/favicon.ico\">\n <link id=\"completeStyle\" href=\"https://www.account.ford.com/static/css/main.d9f26451.chunk.css\" rel=\"stylesheet\">\n <script type=\"text/javascript\" id=\"SCRIPT_RUNTIME\" src=\"https://www.account.ford.com/static/js/runtime-main.f4de8767.js\"></script>\n <script type=\"text/javascript\" id=\"SCRIPT_CHUNK\" src=\"https://www.account.ford.com/static/js/2.cc3aef49.chunk.js\"></script>\n </head>\n <body>\n <noscript>\n You need to enable JavaScript to run this app.\n </noscript>\n <div id=\"ci-error\" data-error-message=\"CSIAQ0154E Das System kann den Client mit ID [9fb503e0-715b-47e8-adfd-ad4b7770f73b] nicht finden.\"></div>\n <div class=\"ibm-ci-data-container\" data-ibm-login-url=\"@ACTION@\" data-ibm-login-error-text=\"CSIAQ0154E Das System kann den Client mit ID [9fb503e0-715b-47e8-adfd-ad4b7770f73b] nicht finden.\"></div>\n <div id=\"page\"></div>\n <script type=\"text/javascript\" id=\"SCRIPT_MAIN\" src=\"https://www.account.ford.com/static/js/main.0229317c.chunk.js\"></script>\n <script>\n\t /*\n\t\t* disable react dev tools in production env\n\t\t*/\n\t\t(function disableReactDevTools() {\n\t\t\tif (\n\t\t\t\t!!window.__REACT_DEVTOOLS_GLOBAL_HOOK__ &&\n\t\t\t\ttypeof window.__REACT_DEVTOOLS_GLOBAL_HOOK__ === 'object' &&\n\t\t\t\t(\n\t\t\t\t\twindow.location.hostname.indexOf('sso.ci.ford.com') > -1 ||\n\t\t\t\t\twindow.location.hostname.indexOf('sso.ci.lincoln.com') > -1\n\t\t\t\t)\n\t\t\t) {\n\t\t\t\twindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.inject = function () {};\n\t\t\t}\n\t\t})();\n\t</script>\n </body>\n</html>"`

`Error: getaddrinfo ENOTFOUND sso.ci.ford.comundefined`

**Comment by TA2k** [comment]
login wurde von ford geändert
bitte mal die GitHub version testen

**Comment by wetterandi** [comment]
Passt wieder! Adapter wird grün und aktualisiert wieder! 
Vielen Dank für Deine superschnelle Unterstützung!
