### ISSUE TITLE
Ford Adapter 0.2.1 startet nicht mehr

### ISSUE THREAD

**Issue by turtok187** [TA2k/ioBroker.ford#34]
**Describe the bug**  
Der Ford Adapter 0.2.1 startet nicht mehr.
Ich habe bei der Domain de, com und ch probiert, erfolglos.

**To Reproduce**  
1. Start and Restart die Instanz

**Expected behavior**  
Der Adapter soll starten ;)

**Screenshots & Logfiles**  
Logfile im Anhang angehängt.
[ford-0.2.1-error-starting.log](https://github.com/TA2k/ioBroker.ford/files/15284033/ford-0.2.1-error-starting.log)

**Versions:**  
 - Adapter version: 0.2.1
 - JS-Controller version: 5.0.19
 - Node version: v18.20.1
 - Operating system: Raspbian 10.13

**Additional context**

**Comment by lurefix** [comment]
Same behavior here.
Adapter doesn't start in version 0.2.1

Versions:
Adapter version: 0.2.1
JS-Controller version: 8.3.0
Node version: v18.20.2
Operating system: Debian 12 VM in proxmox

**Comment by HenkKoopmans** [comment]
Same problem here.
Versions:
Adapter version: 0.2.1
Operating system Debian pi 2.31-13+rpt2+rpi1+deb11u10

Errormessage: Caught by controller[1]: at Ford._stop (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:2213:26)

**Comment by TA2k** [comment]
Bitte 0.2.2 testen

**Comment by HenkKoopmans** [comment]
Seems to work, not fully tested all possibilities yet. Thanks a lot for your fast response!

**Comment by turtok187** [comment]
Danke vielmals für den schnellen Fix! Aus meiner Sicht ist alles OK, du kannst dieses Issue schliessen.

**Comment by lurefix** [comment]
Version 0.2.2 seems to work fine without any problems.
Thanks for the quick troubleshouting.
