### ISSUE TITLE
Wrong state values

### ISSUE THREAD

**Issue by Manolo68** [TA2k/ioBroker.ford#6]
Got some wrong state values in the Info Log:
 (16592) State value to set for "ford.0.xxxxx.statusv2.vehiclestatus.outerRightRearTirePressure" has to be type "number" but received type "string" 
 (16592) State value to set for "ford.0.xxxxx.statususv4.vehiclestatus.TPMS.innerRightRearTirePressure.value" has to be type "number" but received type "string" 
The same on every tire.
 (16592) State value to set for "ford.0.xxxxx.statusv2.vehiclestatus.latitude" has to be type "number" but received type "string" 
 (16592) State value to set for "ford.0.xxxxx.statusv2.vehiclestatus.longitude" has to be type "number" but received type "string" 
 (16592) State value to set for "ford.0.xxxxx.statususv4.vehiclestatus.dcFastChargeData.fstChrgCmpltTEst.value" has to be type "number" but received type "string" 
 (16592) State value to set for "ford.0.xxxxx.statususv4.vehiclestatus.dcFastChargeData.fstChrgBulkTEst.value" has to be type "number" but received type "string" 
 (16592) State value to set for "ford.0.xxxxx.statususv4.vehiclestatus.gps.longitude" has to be type "number" but received type "string" 
 (16592) State value to set for "ford.0.xxxxx.statususv4.vehiclestatus.gps.latitude" has to be type "number" but received type "string"

**Comment by TA2k** [comment]
Are this values correct?
Deleting the values and restart theadapter will work

**Comment by Manolo68** [comment]
Works! Perfect! Thank you!

**Comment by sebaboehm** [comment]
Hello,
I have the same Problem.
Unfortunately the workflow to delete values and restart adapter don't work.



ford.0 | 10273 | 2022-04-04 11:05:23.411 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statususv4.vehiclestatus.TPMS.outerLeftRearTirePressure.value" has to be type "number" but received type "string"
-- | -- | -- | -- | --
ford.0 | 10273 | 2022-04-04 11:05:23.409 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statususv4.vehiclestatus.TPMS.rightFrontTirePressure.value" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:23.408 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statususv4.vehiclestatus.TPMS.leftFrontTirePressure.value" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:23.259 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statususv4.vehiclestatus.gps.longitude" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:23.257 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statususv4.vehiclestatus.gps.latitude" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:23.081 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statusv2.vehiclestatus.outerRightRearTirePressure" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:23.078 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statusv2.vehiclestatus.outerLeftRearTirePressure" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:23.075 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statusv2.vehiclestatus.rightFrontTirePressure" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:23.073 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statusv2.vehiclestatus.leftFrontTirePressure" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:23.065 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statusv2.vehiclestatus.latitude" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:23.064 | info | State value to set for "ford.0.2FMTK4A36KBB16484.statusv2.vehiclestatus.longitude" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:22.855 | info | State value to set for "ford.0.2FMTK4A36KBB16484.details.estimatedMileage" has to be type "number" but received type "string"
ford.0 | 10273 | 2022-04-04 11:05:22.851 | info | State value to set for "ford.0.2FMTK4A36KBB16484.details.modelYear" has to be type "number" but received type "string"
